### ISSUE TITLE
[44078] Customize Failed Authentication Text during Client Portal Login

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#673] opened 2022-08-10 21:21 UTC
Feature request to adjust the following message on a failed login attempt:

"Your email address hasn't been registered and we're not able to automatically create an account for you. Send us an email at support@company.com so we can create an account for you."

>For example, since we use SSO with Office 365 for 99% of our customers use this, but sometimes a user will try to log in and get the message above. It turns out they are just signed into the browser already with another Live or Microsoft account, so I’d want to customize the message to have them go to https://portal.office.com/ and check the account auto-signed in. I don’t have specific wording, but something like this to save us some tickets.

**Comment by Nness** [comment] 2022-08-10 21:51
Developer from DeskDirector, I have checked the code, at the time of error message displayed, our system is not even aware that they logged in with any Office365 account. The problem is related to the email they have entered on initial page.

To get to the error message. Below are steps.

 1. User input their email
  2. User click next
  3. Interface sent email to server
  4. Server check if email is associated with any TECH or portal user
  5. Server sends back report on whether user exist, and whether portal user can be created.
  6. User see the error message if not allow to create new user and no existing user with such email.

The error message will only caused by the email they have entered. To get around for system to check their logged in office account, you can setup catch all company. So the user auto creation is allowed. That way, when the email is not matching with any existing user, it will allow them to create client portal account. 

It is less likely we will change the wording, since it is correct. The user account that associate with email does not exist.

**Comment by Nness** [comment] 2022-08-10 21:55
If they have multiple email associated with their Office365 account, then add those additional email to alternative email of the contact. That should solve the problem.

**Comment by Nness** [comment] 2022-08-18 22:07
I will close this, as the customized content is error message. If error message can be customized, I'm afraid login page alone might have 20~30 different error messages for different scenarios. If there are suggest on better wording on specific scenario, feel free to contact support. Also provide way to reproduce that scenario.

**Closed as completed by Nness** 2022-08-18 22:07 UTC
