### ISSUE TITLE
[46732] DD Portal Removal Tool support for V5.x

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#681] opened 2022-10-26 19:52 UTC
The current DD Portal Removal tool supports versions 2.x/3.x/4.x

https://help.deskdirector.com/article/huqqqba1r0-ddportal-removal-tool-uninstalling-windows-portals

Feature request to include version 5.x as part of this tool.

**Comment by Nness** [comment] 2022-10-26 21:58
We implement uninstall tool mainly due to the chaos of version 2.x. The version 2.x's installation location is branded, which cause uninstall to not working at all. So the logic was to go through all registry and install folder to remove possible version 2.

Since we are out of v2 chaos, there is no intention or reason for us to support latest v5. Maybe in the future, there are registry or file that didn't clean up by MSI, we might implement different script to clean up.

All in all, we are less likely to involve on existing removal tool. The intention was only cover desktop portal Electron version's leftover junks.  And it has achieved it needs.

Version 5 is native .net based, registry also handled by MSI. The only possible junk was setting and logo file. So far they have been cleaned up by MSI. 

I will close this until we have solid reason. Such as what is missing, what kind junk was left behind that we need such removal tool.

**Closed as completed by Nness** 2022-10-26 21:58 UTC

**Comment by RyanScottT** [comment] 2022-10-31 09:51
The reason for this request is the possiblity of our clients requesting the latest v5.0*** being removed from all devices. The current uninstaller provided does not work with v5 as confirmed with the DD support team  

If a new version is being released then surely an uninstaller should be released also to ensure for any reason, the application being installed can be uninstalled cleanly without per device, manual intervention. Why would you not support a new version you are releasing?

**Comment by Nness** [comment] 2022-11-01 20:30
@RyanScottT  You can use MSI to [uninstall](https://learn.microsoft.com/en-us/windows/win32/msi/standard-installer-command-line-options#quiet) the application. Or you can use RMM to uninstall, labtech can do that as well, I believe.

We never need to release uninstaller, only due to v2 we had folder branding, and plus v2 and v3 both have left over during uninstallation. So we have to create uninstaller to resolve issue. This shouldn't be the case for new installer. There were a lot of mistake we have made on v2 and v3, the script is only there to fix issue not for ordinary uninstall and we have no intention to maintain such project as we moving forward.

The script was only created for the mess we have caused in v2 and v3. I was not expect v4 to be added to script.
