### ISSUE TITLE
REWST Integration RPA

### ISSUE THREAD

**Issue by NetFusionDesigns** [DeskDirector/UserVoice#740] opened 2024-02-07 12:12 UTC
We would like to see DeskDirector integration with REWST, I’m sure many others would as well.

REWST is the fastest growing MSP RPA platform, being able to parse DD info into a REWST form can automate a number of tasks including user onboarding, offboardings and password reset

**Comment by Aycorn** [comment] 2024-11-18 02:35
Duplicate of the following: https://github.com/DeskDirector/UserVoice/issues/739

**Closed as completed by Aycorn** 2024-11-18 02:35 UTC
