### ISSUE TITLE
Schedule/Assign other resources from DD Tech.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#178] opened 2018-10-29 19:30 UTC
![image](https://user-images.githubusercontent.com/30588784/47675177-12f55e00-dc1e-11e8-99fc-43bca60101eb.png)

In the same area where you can select 'Assign Me' there should be another button that just says 'Assign Resource' or something along those lines. This should give you the option to select from a drop down list or type members names in that you would like to have assigned against the ticket. You should also be given the option to schedule these members in with a calendar of sorts like you currently do.

The main reason for this is that a lot of service desks will have a 'dispatcher' that will assign that work out to people. DD Tech doesn't allow for that occur and just assumes that your engineers will go in and self assign them work - which just leads to engineers picking and choosing what they want to work on. Something we want to avoid.

**Comment by Andrew-Lahikainen** [comment] 2018-10-30 20:12
I think this request makes sense, but in general we should avoid adding features for users that are outside of Tech's target audience. I don't think Tech will be suitable for dispatchers because we have spent no time understanding the needs of this role. Perhaps in the future we can start thinking about these other types of users and evolve Tech to meet their needs.

**Comment by sdcoyl** [comment] 2018-10-30 20:14
I do think that from the tech view they should be able to assign internal resources. Different teams have different skill sets and focus.



Thanks,


[cid:image001.png@01D4455D.494794D0]

[Logo]

Sam Coyl

President/CEO

T: 717-730-0780<tel:717-730-0780>

E: sam.coyl@netrepid.com<mailto:sam.coyl@netrepid.com> | www.Netrepid.com<http://www.netrepid.com/>

2330 Vartan Way, Suite 185 | Harrisburg, PA 17110<x-apple-data-detectors://0/4>

[LinkedIn icon]<https://www.linkedin.com/company/netrepid> [Twitter icon] <https://twitter.com/netrepid>


[cid:image005.png@01D4455D.494794D0]


On Oct 30, 2018, at 4:12 PM, Andrew Lahikainen <notifications@github.com<mailto:notifications@github.com>> wrote:


I think this request makes sense, but in general we should avoid adding features for users that are outside of Tech's target audience. I don't think Tech will be suitable for dispatchers because we have spent no time understanding the needs of this role. Perhaps in the future we can start thinking about these other types of users and evolve Tech to meet their needs.

-

**Comment by virtuist** [comment] 2018-11-02 21:18
I do agree with both sides of this, I don't see a dispatcher using this, but there are many times when technicians need to assign a ticket to a different technician because the dispatcher wasn't available or assigned it incorrectly.  There are also many times that the technician needs help from another technician and would need to add an additional resource.  A third reason it would be great is if you're working with a streamline IT user and they need to escalate a ticket to your team or offer help.  At the very least, I think it would be an awesome feature to add for some technicians, especially team leads.

**Comment by sdcoyl** [comment] 2018-11-06 22:10
I would simply reiterate that we do have a variety of skill sets using this. Dispatchers are not really the key audience. We would have L1 L2 and architects managing tickets through this. They need to be able to assign them to boards as well as other resources.

**Comment by Andrew-Lahikainen** [comment] 2018-11-16 03:02
I agree! I think this feature should be added. My concern was more of a general one, because the OP suggested that dispatchers need this functionality. In general I don't think we should add features piecemeal for roles we haven't planned for.

**Comment by Andrew-Lahikainen** [comment] 2018-12-14 02:32
This is a duplicate of https://github.com/DeskDirector/UserVoice/issues/49

**Closed** 2018-12-14 02:32 UTC
Labels: backlog, core, duplicate, tech
