### ISSUE TITLE
[11951] Disable the "Something Else" generic form.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#172] opened 2018-10-08 01:35 UTC
![image](https://user-images.githubusercontent.com/30588784/46589537-0c843280-cb07-11e8-84b5-dd63a3d716a1.png)

This currently provides a path of least resistance for customers, however this also limits the information available on the ticket being submitted.

Often a company would prefer to have customers fill out the custom created forms as all the requested information is provided.

**Comment by Nness** [comment] 2018-10-09 23:34
This is declined unless there is compelling reason.

The design decision made here is to help our customer to maintain their client relationship. From our current understanding if remove that it will act opposite.

Let's dive into this issue. Why is end user have low resistance on this choice?
1. There are too many categories, user cannot figure out which category to dive into
2. There are too many request types, user cannot pick and choose which one for their problem
3. The form inside request type is too hard to answer, and it is marked as required. Thus they submit through something else.

Let's put in this way. If request types page design too complex, as a user I will use email if you don't provide escape point. That's the experience I have when I use portal everyday. When I submit through email do you have to serve me? Yes you still have to. Do you have to categorize my ticket? Yes you still have to. Is categorize ticket end user's job? No. Is request types a tool to categorize ticket? No.

Portal is not a place for service provider to move responsibility to end user side, it is service provider to provide good environment to serve their customer. Not other way around. 

Certain form can make ticket resolve faster, sure, do we need more than 10 forms for every end user? What kind of request this company's user request most often? Can a form decrease the time to resolve ticket? Those are questions to ask before create request type. The key for this is **less is more**.

If put in practice test, design request types and pass to one of family member you have that have no IT knowledge, can they navigate around easily? Can they answer those forms easily?

One of the example I have seen is printer have issue. And inside form it has several question marked as required. One of question is, what is name of printer that had issue? As developer I feel shame that I cannot answer that question directly. What kind of name do they refer to? Name display inside print screen? Name of printer brand? I can tell you it is at which location easily not name.

**Comment by Nness** [comment] 2018-10-09 23:36
Above is reason behind several design decisions.

* Not allow more than 2 tiers inside request type. from user experience point of view, more than 1 tier is hard for human to remember, more than 3 tiers is impossible.
* Have escape route on create ticket
* Form's required field (this one is there, but at one stage was considered is needed or not).

**Comment by FluidNets-DamianS** [comment] 2018-10-09 23:44
@Nness I agree with your logic.  You can create more complex forms for more through tracking of ticket data, but it needs to be end-user friendly at all times.  We use the logic of:

Category:   I am have a problem with...
Request Type:   ...my Printer
This give me my ticket type, sub-type and item (Hardware, Printer/Copier, Error)

Then we have a few yes/no questions to determine priority (which are required)
1. Are you the only user having this problem?
2. Are you able to work around this issue?

Then we have the text box of "Please describe the problem you are having".  Some of our forms ask the user if there is an error message and if so we display another text field just for that error.

**Comment by jfsniperz** [comment] 2018-11-05 22:12
This is also a problem with companies with a pod-setup (clients configured with their specific boards).
If we can't have the option of disabling this generic form, please allow setting default boards for each client, so tickets from this form will go to the right board and not get lost in another board.
https://github.com/DeskDirector/UserVoice/issues/187

**Comment by Lowell-Syncrety** [comment] 2018-11-10 00:57
I fully agree with this being an optional thing and not forced on us.  The reason is, I *already* have a form called "I have an issue not listed here" that still gets key information like how quickly would you like this addressed, etc. which is now likely to be bypassed by your mandatory form.

Instead of forcing your workaround on our design and service delivery, why not pop up a note when we go to disable that option, telling us to make sure we have a similar form in place?  Better yet, you make one already and suggest we make sure that one is set to Active if we're going to disable this feature?  Options are always better than forcing.

**Comment by Andrew-Lahikainen** [comment] 2018-11-15 03:29
Duplicate of https://github.com/DeskDirector/UserVoice/issues/109

**Comment by Andrew-Lahikainen** [comment] 2019-01-30 22:13
This has been implemented. You can disable this globally here:

![image](https://user-images.githubusercontent.com/10571313/52016340-1f54c400-2549-11e9-8fdf-92d86e27b3bc.png)

**Closed by Andrew-Lahikainen** 2019-01-30 22:13 UTC
Labels: admin, completed, duplicate, portal

**Comment by Lowell-Syncrety** [comment] 2019-01-30 23:31
Awesome, thanks!!
