### ISSUE TITLE
[23329] Advanced Search for Contacts page

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#474] opened 2020-08-24 23:14 UTC
As an addition to the current search field, feature request for an additional "Advanced Search" option.
This would contain fields to better identify contacts based on exact matches:

- First Name:
- Last Name: 
- Email Address:

**Comment by Nness** [comment] 2020-08-24 23:28
Email address is already working, just put email address inside search input.

First and last name, if type correctly, it should be on top most.

**Comment by Nness** [comment] 2020-08-24 23:49
Close this for now, most likely customer don't know they can type in multiple word, or type in email. Feel free to open when there is solid example to demonstrate the issue.

**Closed by Nness** 2020-08-24 23:49 UTC
Labels: admin

**Comment by cdandrea** [comment] 2020-08-25 00:29
The problem is when you have multiple hits for the same email address. If a contact is associated with numerous clients, e.g. primary contact across a franchise group of companies, they will come up multiple times. If we type a first and last name, it doesn't always show the best match along the top. There may another instance of a matching name further below. We won't always have the email address on hand, so typing first and/or last is fairly common.

A prime example is if I know the first name and last initial, e.g. "Adam C" I will get 138 hits across my contacts. I don't understand what the logic is --- [screenshot](http://sharing.caseydandrea.com/JYrPpf9)

I think a simple sort option, would likely address the problem entirely.

**Comment by Nness** [comment] 2020-08-25 00:31
Adam C is not valid example, could you try full name?

**Comment by Nness** [comment] 2020-08-25 00:32
Even typo is fine, try type in full name.

**Comment by Nness** [comment] 2020-08-25 00:33
![image](https://user-images.githubusercontent.com/1712143/91109461-25803780-e6cf-11ea-9656-98b23eecde93.png)

This search helper dropdown will display on next admin portal release.

**Comment by Nness** [comment] 2020-08-25 00:34
You can even type in following in same term:
```
arnie bellini connectwise.com Arnie@ConnectWise.com
```

**Comment by cdandrea** [comment] 2020-08-25 01:11
@Nness those are fair options, however the point of doing a search is you won't always have the full name on hand. If you type first and last name, e.g. Adam Dixon, I indeed get all the exact hits towards the top. However, can you help me understand the logic of the remaining 100 hits, as they appear arbitrarily sorted after those initial matches.

It seems that search doesn't include partial matches, to your earlier point. It only find exact string matches. For example, if I type "Adam" and "Euro" I match on a user name "Accounts Payable" from "Euro RSCG Life" -- the closest match being a full word from the company name.

However, if I type "Adam" and "Europtimum", it properly matches on "Adam Dixon" from "Europtimum display". I think it may be word adding to the helper text that partial word matches are not valid.

Is there a sort option on the horizon? :)

**Comment by Nness** [comment] 2020-08-25 01:18
It will never have sort option if search been used. This I can guarantee. 

I would suggest to treat our search as google search. It's not contains, nor start with. If you type `Adam Europt` it should give you correct result.

`Euro` itself match both `Euro*` and `Euro`. And `Euro` exact match makes it higher rate than non exact match. That's why Company name with `Euro` appear first.

Remaining 100 hits should be in some way match.

You have to think about start with will give rating of 1 and exactly match will give rating of 2. Repeat appear will add rating together. Also if char less than 3, it won't search for start with. Since that's massive amount of match.

**Comment by cdandrea** [comment] 2020-08-25 01:40
Thanks for the clarification. The breakdown helps explain the logic. Much appreciated. And I agree, that sort is extremely slow by comparison.

**Comment by Nness** [comment] 2020-08-25 02:38
I have just created an article to detail out our search engine.

[How search works in DeskDirector](https://help.deskdirector.com/article/09gt8a3cb2-how-search-works-in-desk-director-products)
