### ISSUE TITLE
[13586, 10876] Create forms/tickets on behalf of other users

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#54] opened 2018-06-19 03:56 UTC
Would like to be able to create tickets or forms on behalf of a different user within same company.

**Comment by FluidNets-DamianS** [comment] 2018-08-04 17:03
@Nness what would be a rough eta for this solution?  We originally asked for it over a year ago and now that we are using DDp 100% I have some clients with torches and pitchforks coming after me.  I need to get an idea on where this is on your guys roadmap as if it is too far out or unknown I will have to come up with another option to jimmy-rig it....

**Comment by bobsquid** [comment] 2018-08-06 02:29
I can say from my side that this is a daily occurrence.  We have many clients that use a single point of contact to open tickets for all of their users, so this is absolutely critical to my business as well.







  [cid:SIG-Pace_8cec8766-e136-4573-a78e-d5a13ed878ed1111111.jpg] <http://www.pacetechnical.com/>


Jay Da Costa
Director of Service Delivery
905-763-7896 x226


[cid:SIG-Great_55f3a646-6146-45d5-ba1c-023fd59406b41111111.jpg]<https://www.greatplacetowork.ca/en/best-workplaces/best-workplaces-in-canada-small><http://www.greatplacetowork.ca/>


[https://web.crewhu.com/external/v1/dashboard/csatWidget/59afff2ba89e9251839a8abd]


[cid:SIG-msp_00fb0681-886b-424b-abb2-1cc5a88c12971111111.jpg][cid:SIG-mspartner_479d07c5-a784-4b62-8641-3a2089a2c5f61111111.jpg]






-------- Original message --------

**Comment by FluidNets-DamianS** [comment] 2018-08-06 10:49
Yes I would expect them to submit via our DD forms.

This issue is that this is a core CW portal feature that has existing for years.  Only (2) of our clients allow end-users to submit requests directly.  Mainly this is due to the issue of controlling cost however there are other client reasons for this as well.

Another use is that Joe's computer is not turning on so Joe cannot submit a ticket.  Jane his neighbor submits the ticket for Joe but since she selected Joe as the contact our tech team knows to contact Joe about the issue and not Jane.

In our POC scenario in which 95% of our customers fall the POC submits an approved request but wants us to contact the end-user directly.  However without selecting the correct end-user contact our techs have to think, then look up correct contact info etc...

This is a huge issue for us.  As I originally submitted last year ticket #6144.

Yes, technically the approval process does alleviate some of the control issues but not all.  In addition we do not like using any approval processes unless a customer really demands it.  This is due to a ticket being submitted, the approver being out for a few days and the ticket sitting while the end-user expects something to be progressing.  Again that would address the scenarios I gave earlier.

On your last question yes this prevents too many tickets, repeat tickets as well as unsupported tickets from being created.  This however is not our issue but something all of our clients request and again expect as they have always had the feature and control in the ConnectWise portal.

**Comment by bobsquid** [comment] 2018-08-07 13:12
It is exactly the same on my side.  Sometimes a user needs to open a ticket for their colleague who has a computer down, but mostly it is due to the client's internal processes.  If a client wants to do things this way and they have always been able to in CW, it's an extremely inconvenient for them to no longer be able to do this.  A big selling point for DD from a client perspective is that it should be making their life easier, not more difficult.

**Comment by Nness** [comment] 2018-08-07 22:43
To understand the scope better. We currently have permission of all tickets access. Current plan is to allow people who can access all tickets to create ticket on behalf of other contact, but given the scenario of user log ticket for other user if their computer is broken, then it doesn't means everyone have such permission to create ticket on behalf of others right?

**Comment by FluidNets-DamianS** [comment] 2018-08-07 22:59
If user has all ticket access then they should be able to create for any user.  That is the core that exists in CW.  For normal users it could go either way.  Best scenario would be to let them create ticket for other user and automatically add them as a CC to the ticket.  However the 1st item is the critical one.

**Comment by Nness** [comment] 2018-08-08 02:44
Cool Thanks for information.

**Comment by FluidNets-DamianS** [comment] 2018-08-11 19:38
@Nness I know I asked this before but do you have a rough eta for this functionality?  Something like less or more than 6 months to figure what we will do to appease some angry customers.

**Comment by Nness** [comment] 2018-08-12 21:47
I could not give any accurate eta. One thing for sure is unless it is a bug, it won't be put into roadmap until end of Oct.

Currently, development team is running a 3 months cycle. Once set a goal for that 3 months period, we will be focus on that until next cycle.

Thus, on early Nov, we will sure what we will be focus on for next 3 months. 

There are two options before official implementation.

1. Zapier or Flow
You are familiar with Zapier, the idea is inside form, provide an input to ask for email. If email got filled in, then Zapier and flow can change contact of ticket to that given contact.

2. New menu system
This is one of focus in this development cycle, which we want to provide a secure way for 3rd party extension site to be live on. That means people can develop extension site that consumes DD API.

Zapier and Flow is most easiest option available now.

**Comment by bobsquid** [comment] 2018-08-14 17:40
I am new to Zapier.  Is there a guide to how to set this up?

**Comment by FluidNets-DamianS** [comment] 2018-08-14 17:57
@bobsquid you will need to webhook your form to zapier, then process the data and make an API call back to update the ticket.  You can probably do the latter via DDapi or you can use the ConnectWise connector in Zapier.

**Comment by FluidNets-DamianS** [comment] 2018-11-10 01:49
@Nness is there any update regarding the new menu system?

**Comment by Nness** [comment] 2018-11-15 04:45
Sorry for late reply. Menu system back end is done and we also have admin console ready as well. What we need to do in next quarter is make sure portal supports it. New menu system is in next quarter plan. Full quarter plan should be finalized within next 2 weeks.

**Comment by Aycorn** [comment] 2019-01-20 22:58
Similar Request: Service Ticket #13586 - put tickets in for other users

**Comment by Nness** [comment] 2019-01-21 22:22
@FluidNets-DamianS issue #12 is for new menu system.

**Comment by FluidNets-DamianS** [comment] 2019-01-22 00:20
@Nness ok I know past discussions caused some overlap.  Is there any progress on this particular request.  (submit requests on behalf of other users) Again it is core functionality that exists in CW and we receive complaints constantly.

**Comment by Christina-FantasticIT** [comment] 2019-01-25 18:57
Our company would greatly benefit from this feature as well.

**Comment by Nness** [comment] 2019-01-29 00:59
@FluidNets-DamianS @Christina-FantasticIT 

I have been discuss with other core members on this feature last week. One of functionality will come out in near future is ability to modify ticket inside portal. End user will be able to modify ticket subject and ticket owner.

That way POC can create ticket first then change the owner to other contact.

I believe that's first step towards resolve this issue. 

The earliest for ticket update feature would be March.

**Comment by chris-ls** [comment] 2019-04-15 08:37
A Point of Contact (POC) is defined as anyone who has the "All Tickets" permission inside DeskDirector.

The POC will be able to modify the Ticket Subject/Summary/Title and the Ticket Owner.
Thus the flow for this use case is:
* POC creates a ticket or submits a form.
* The ticket is created with themselves as the Ticket Owner.
* The POC then navigates to that Ticket and reassigns the Ticket Owner to another contact within their company.

If you have any thoughts on this, any limitations or issues you can see, please leave some comments below :)

This will be released in early May subject to no major issues around this functionality popping up.

**Comment by AirLHull** [comment] 2019-04-15 09:33
We use "All Tickets" in a similar way however with our large clients, managers will have this access who i would not define as "Not a point of contact".

Although the idea of this great, is this feature a turn off/ on feature or always on? I believe that we have clients that will and will not benefit from this feature, as we have created a form "I would like to raise a case on behalf of another user" and used this for the time being.

By the term "Ticket Owner" are you also referring to the main contact on the ticket?

**Comment by chris-ls** [comment] 2019-04-15 21:37
> We use "All Tickets" in a similar way however with our large clients, managers will have this access who i would not define as "Not a point of contact".

Do you mean, 'would not define as "~~not~~ a point of contact"' ? Sorry the double negative has me confused :)

> By the term "Ticket Owner" are you also referring to the main contact on the ticket?

Sorry yes, this is referring to the main contact on the ticket.

This feature was not planned to be turn on/turn off.
The assumption was that any contact who has "All Tickets" access, is in a position where they are trusted with the ability to reassign tickets within their own company. They could choose to use/not use the feature themselves.

What issues would arise if this was suddenly made available to your users with All Tickets access?
Is there some kind of information you may miss out on?

**Comment by AirLHull** [comment] 2019-04-16 15:46
Hi Chris

Apologies for the confusion! "Managers will / may have all ticket access however they may not be defined as a "Point of Contact" for the client / company" (Looked at it again and i know what you mean!). To us a point of contact would also be able to be an approver / quote viewer / invoice viewer etc.

Agreed that most people who have all ticket access should be able to be trusted with changing this around.

I may have misunderstood this overall to be honest, they could change the Ticket Title / Main Contact on the case but the CANNOT change the Types / Subtypes / Priorities etc is that correct?

We do not want the client to be able to change too much as our reporting is heavily dedicated to the almost all fields within the ticket. If they can change just the ticket title and main contact of the case i cannot see this being a issue to be honest!

If you catch my drift :)

**Comment by chris-ls** [comment] 2019-04-17 00:24
> I may have misunderstood this overall to be honest, they could change the Ticket Title / Main Contact on the case but the CANNOT change the Types / Subtypes / Priorities etc is that correct?

Yes that is correct, they will only be able to change Ticket Title / Main Contact.

**Comment by FluidNets-DamianS** [comment] 2019-05-04 12:48
Just checking on the status of this since we are now in early may...

**Comment by chris-ls** [comment] 2019-05-08 01:01
Work has begun on this.
Expect this to be available in the Web client late this week or early next week.
It will be available in the Desktop client approx 1-2 weeks after that, as the Desktop gets a delayed rollout.

**Comment by chris-ls** [comment] 2019-05-15 04:35
This is available now inside the Web Client.
Feedback appreciated.

**Comment by cdandrea** [comment] 2019-05-15 05:03
I'm trying to understand how this is implemented. I'm not seeing the ability to change the ticket owner when expanding the details in the ticket. Is this another feature that is not available in the new UI?

**Comment by FluidNets-DamianS** [comment] 2019-05-15 05:13
I do not see this feature either


Damian C. Stalls
vCIO Director
805.856.1815 Direct

________________________________

**Comment by cdandrea** [comment] 2019-05-15 05:14
Never, it looks to be the case. This is disappointing. This is following the same path as the Approver feature not being available in the new UI either. To be clear, the option **Enable Portal V2** works fine when enabled, but it seems when enabling the child option **Enable the new ticket interface (Alpha - Intended for test only)** is when we lose the ability to alter the ticket details as it's now positioned above the ticket conversation.

On a positive note, it appears that Approval **does** work, but only if the child option **Enable the new Request Support Interface** is **unchecked**. So it seems they are regarding differently.

**Comment by FluidNets-DamianS** [comment] 2019-05-15 05:21
I see it now.  Will play with more tomorrow.  Functionality is ok, many users will still complain that they have to go back into the ticket to edit.  Should be part of the initial request.


Damian C. Stalls
vCIO Director
805.856.1815 Direct

________________________________

**Comment by cdandrea** [comment] 2019-05-15 05:30
@FluidNets-DamianS - I've done what others have mentioned and added a condition within my forms to inquire whether the request is for themselves or on behalf of someone else. It's a little clunky and still requires the manual adjustment of the ticket contact in CW after the fact, but at least it allows the client to communicate that up front.

The other consideration was somehow mapping form fields to specific attributes of the ticket. In a similar manner that request types can define a submissions type, sub-type, priority, etc. Still trying to figure that part out. There seems to be some possibilities with the Ticket Title/Body Template area of the request type

**Comment by chris-ls** [comment] 2019-05-16 01:09
@cdandrea 

> I'm trying to understand how this is implemented. I'm not seeing the ability to change the ticket owner when expanding the details in the ticket. Is this another feature that is not available in the new UI?

This feature isn't going to be immediately available in the new UI. 
It will definitely become a part of it in the future when we start working on it again.

Just to clarify about the new Ticket interface.
The new UI is *not* ready for a public release at this time.
When we put the checkbox to **"Enable the new ticket interface"** into the Admin Console, it was intended to be used only by beta-testers.
We messed up here; this option should never have been visible in this location next to other feature flags.
Several customers have turned this feature on without realizing it wasn't production ready.
We added the *Alpha - intended for test only* piece so that our customers would see this and turn it off again.
We will shortly be turning it off altogether but wanted to give customers the chance to turn it off themselves first.

Work has been temporarily delayed on this UI, but will be continuing shortly.
The design will almost certainly have alterations.
When we finally release, it will also come along with a redesign of the ticket list.

**Comment by FluidNets-DamianS** [comment] 2019-05-16 01:16
I think we were the source of that long ago.  We have the question if this is for you or another user as well as if the user has a work around (to control escalation).

Also, for the type/sub type we have a form built with all the options.  Based on what is selected we have an excel table where we do a look up (via Zapier) and then update the ticket accordingly.  This is mainly as we make the form end-user friendly:

Example:

  *   Application
     *   Google Chrome                             = Application / Google Chrome
     *   Internet Browser
        *   Google Chrome               = Application / Google Chrome
        *   Internet Explorer            = Application / Internet Explorer

A user looking to report an issue with Google Chrome may only think to look for Google Chrome or Chrome.  A more tech savy user may look for a category for browsers.  We do a back end look to normalize then update the ticket via API.

Damian

**Comment by Nness** [comment] 2019-10-13 20:14
@FluidNets-DamianS 
@cdandrea 

To give an update on ticket listing and detail interface v2. It now allow to change ticket owner and title. But the interface is not yet fully complete. Though many have already been using it.

I have reviewed few upcoming changes to portal at post [here](https://github.com/DeskDirector/UserVoice/issues/134#issuecomment-541453059). The ticket detail might look like following screenshot in near future.

Few things we want to improve on existing v2 UI are:
* Similar clean note feature as TECH. (remove reply content, clean up URL)
* Make attachment subtle. so user can focus on ticket note a bit more.
* easier access to information regard to ticket owner, priority etc. Instead of clicking on detail button.

Feel free to give any feedback on this.

![Web 1920 – 2@2x](https://user-images.githubusercontent.com/1712143/66721753-45658e80-ee62-11e9-8483-10bd906cba03.png)

**Comment by Andrew-Lahikainen** [comment] 2019-10-18 04:54
This ux has been deployed. Head to the feature preview page in the admin console to turn it on (tickets v2)

**Comment by Andrew-Lahikainen** [comment] 2020-01-31 01:32
shipped

**Closed by Andrew-Lahikainen** 2020-01-31 01:32 UTC
Labels: core, open beta, portal
